### ISSUE TITLE
expose healthz port or something for health check

### ISSUE THREAD

**Issue by alin04** [ampproject/amppackager#186]

**Comment by ireinhart** [comment]
Hello,

we are trying to use the amppackager for our site. Is it possible to add a small health check endpoint? We like to monitor the service and use the kubernetes livenessProbe.

**Comment by alin04** [comment]
Yes, that was the idea - to support containers like kubernetes and Docker.

The thought is to check the cert cache is healthy and the rtv cache is up-to-date.

We probably won't be able to address this for another month or so. Feel free to submit a PR.

**Comment by FranGM** [comment]
Hey, since this issues seems to be in progress I thought I'd ask what's the status/ETA on this?

If we know when to expect (or don't expect) the health check endpoint to be available we can make a decision on how to work around it or not.

**Comment by Gregable** [comment]
I picked this up during a Fixit week we had ~2 months ago, but was interrupted and did not make much progress. It has languished since. 

@twifkak @banaag do you think a basic health check could be prioritized in the near future? The main things to verify are probably that reading the toml didn't fail, we have a valid certificate, and OCSP response.

**Comment by Gregable** [comment]
I don't have a particular deadline in mind. @FranGM what would be a useful timeline for you to avoid having to work around this?

**Comment by FranGM** [comment]
I think we're looking at around 2-3 weeks for going live. Can probably live with something like a port check for dev/testing but before we get to production we'll certainly want something a tad more robust, which is why I'm trying to plan ahead a little bit.
