### ISSUE TITLE
Packager should coerce documents to be interchange valid UTF-8

### ISSUE THREAD

**Issue by Gregable** [ampproject/amppackager#252]
If a document is not interchange valid UTF-8, it cannot be served as a signed exchange. The packager should attempt to coerce non-valid strings to valid.

**Comment by twifkak** [comment]
"Interchange valid UTF-8" doesn't turn up a canonical-looking source on the internet. Does [this definition](https://github.com/tensorflow/models/blob/master/research/syntaxnet/util/utf8/unilib.h#L50) seem right to you? Do you have a proposal for how the coercion should work? (Strip the invalid code points? Replace them with some other char?) If it's an infrequent-enough occurrence, I'm usually inclined to play it safe and just error out (proxy unsigned).

**Comment by Gregable** [comment]
Yes, that definition seems right.

There is some code in the related AMP Cache issue in 126725658 that may be of help for coercion. Proxy unsigned as a first attempt seems reasonable.

**Comment by honeybadgerdontcare** [comment]
Should something also be done in transformers.go for this since some sites may use transformers.go and not the full packager? Either a check that it is interchange valid UTF-8 or a coercion?

**Comment by Gregable** [comment]
Any of these options would probably work.

**Comment by twifkak** [comment]
OK, it appears that IsInterchangeValid is equal to the characters that cause HTML preprocessing [parse errors](https://html.spec.whatwg.org/multipage/parsing.html#preprocessing-the-input-stream), plus U+0000 NULL, which causes HTML parse errors everywhere except CDATA. This seems like a reasonable requirement.

NULL seems especially dangerous at first glance -- in several cases, in causes the HTML parser to change state. So if we allowed it inside CDATA, we'd be relying on exact parity of what-is-CDATA between the various HTML parsers of the world.

We could loosen the requirement given that browsers will display pages with parse errors, and the spec defines how to handle these errors. However, doing so would again depend on the correctness of the various parsers at play in this ecosystem, and this seems in line with the [recommendation for correctness checkers](https://html.spec.whatwg.org/multipage/parsing.html#parse-errors).

I'll code something up so that the packager proxies unsigned in these cases, since we can check quickly, and know they'll fail validation anyway. (Complete AMPHTML validation is outside of the scope of this packager, as it is more costly than I'd like to add without caching, and besides we don't have a Go impl.)

**Comment by twifkak** [comment]
Fixed by commit 0b348d86 (#268).
