### ISSUE TITLE
End-to-end headers for fetchURL

### ISSUE THREAD

**Issue by shigeki** [ampproject/amppackager#259]
In addition to https://github.com/ampproject/amppackager/pull/256, we need to set our own end-to-end headers in fetchURL for generating our AMP pages.

For resolving this issue, I think that the fix would be make with either of the following two methods.
- Copying all request headers except hop-by-hop to fetchURL
- Specifying header names to be set for fetchURL in the config

Which is better? Or is there anything else to resolve this?

**Comment by twifkak** [comment]
My preference is for the second option, but I could be swayed. What I'm worried about is a default behavior that [over-signs](https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#seccons-over-signing). Requiring `AMP-Cache-Transform` reduces the chance that the request comes from a user agent, but doesn't eliminate it. (For instance, our documentation [recommends](https://github.com/ampproject/amppackager#productionizing) that developers add a Chrome extension to set the header, in order to test.)

If we chose "copying all request headers", I'd want a decent degree of confidence that they've been scrubbed of anything that could be used to fingerprint the user (e.g. `Cookie`, etc.). Off-hand, I don't know what the full list of things that need to be scrubbed is.

**Comment by shigeki** [comment]
Thanks for your comment. I agree there is a risk to copy all the request headers blindly and it is better to have a whitelisted header name list in the config. I will work it in the next week.

**Comment by twifkak** [comment]
@shigeki Are you still working on this (or planning to)?

**Comment by shigeki** [comment]
@twifkak Sorry for being late. I'm now busy in preparation for AMP Conf. This feature is really needed for our SXG deployment. Please wait for a while.
