### ISSUE TITLE
What means "Error computing OCSP midpoint: Parsing OCSP: no response matching the supplied certificate"?

### ISSUE THREAD

**Issue by ireinhart** [ampproject/amppackager#273]
Hello!
Hope you can help me, at this question.  If I start the amppackager, the service log this:

```
2019/04/02 09:30:05 Updating OCSP; none cached yet.
2019/04/02 09:30:05 Updating OCSP; none cached yet.
2019/04/02 09:30:05 Error computing OCSP midpoint: Parsing OCSP: no response matching the supplied certificate
2019/04/02 09:30:05 Error computing OCSP midpoint: Parsing OCSP: no response matching the supplied certificate
2019/04/02 09:30:05 Fetching URL: "https://cdn.ampproject.org/rtv/metadata"
2019/04/02 09:30:05 Fetching URL: "https://cdn.ampproject.org/rtv/011903262220080/v0.css"
2019/04/02 09:30:05 Serving on port 8080
```
It seams to me, that it works.

But I don't understand what the message "Error computing OCSP midpoint: Parsing OCSP: no response matching the supplied certificate" means?
Can I ignore them or should I do something?

Best,
Ingo

**Comment by twifkak** [comment]
I'm sorry the OCSP error messages are so confusing. I think you can ignore that error _only if_ you see a later success message, which looks like: `No update necessary.` Since I don't see that above, I suspect there may be an issue.

If things are working, you should be able to run:
```
curl -H 'Accept: application/signed-exchange;v=b3' -H 'AMP-Cache-Transform: google;v="1"' http://localhost:8080/priv/doc/https://path/to/amp.html | less
```
(for some path/to/amp.html) and see that the response starts with "sxg-b3".

If it doesn't, then this is further evidence of an issue with the OCSP. In that case, take a look at the file path you specified at `OCSPCache` in `amppkg.toml`. Does the file exist and have more than 0 bytes? If so, try inspecting it:

```
openssl ocsp -text -respin path/to/ocspcache -noverify
```

and make sure it looks good (e.g. `status: successful`, and `This Update` < now < `Next Update`), and that its `Serial Number` corresponds to the serial number from the cert you specified in `CertFile`:

```
openssl x509 -in cert -text -noout | grep -A1 'Serial Number'
```

This isn't a [full verification](https://raymii.org/s/articles/OpenSSL_Manually_Verify_a_certificate_against_an_OCSP.html) of the OCSP response, but may be enough for an initial diagnosis.

**Comment by ireinhart** [comment]
Many thanks for your support.
It is like you wrote :-)
