### ISSUE TITLE
Steep decline in the number of pages crawled by google

### ISSUE THREAD

**Issue by cw-pratik** [ampproject/amppackager#351]
Recently we started serving AMP pages through signed exchanges.
We saw a steep decline in the number of pages crawled by google (from 449k to 121k) in a span of 2 days.

After that we reverted the change and the number of pages crawled was back to normal. (460k)

Is there any specific reason why there would be such a decline?
Is there any negative impact because of this?

**Comment by twifkak** [comment]
Sorry to hear that. There's a couple of reasons this may happen. To diagnose, I would enable signed exchanges for just a few URLs, and then validate a few different things:
1. Verify it looks like an SXG response. Run something like `curl -i -H 'Accept: application/signed-exchange;v=b3' -H 'AMP-Cache-Transform: any' $SOME_URL | less`. You should see a response header of `Content-Type: application/signed-exchange;v=b3` and a response body that starts with "sxg1-b3".
2. Verify sure the SXG is well-formed. Run the above `curl` but without the `-i` flag and save it to a file with `>somefile.sxg`. Then run `go get -u github.com/WICG/webpackage/go/signedexchange/cmd/dump-signedexchange` to install, and run `~/go/bin/dump-signedexchange -i somefile.sxg -verify`. The `-verify` is important because it checks MICE encoding.
3. Verify the "uri" printed by `dump-signedexchange` is exactly equal to the URL that you `curl`ed. They must be byte-exact -- even changes in percent-encoding are disallowed.

If there are no obvious errors, then please share a URL and we can help debug. If you prefer to share the URL privately, you can DM me on [AMP Slack](https://bit.ly/amp-slack-signup). (Sorry the process is a bit manual right now; we're working on improving that.)
